version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /etc/nginx/conf.d
    - ./certs:/etc/nginx/certs
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
  dockergen:
    image: jwilder/docker-gen
    container_name: redwood-docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
    - nginx
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./conf/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
  letsencrypt-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: redwood-letsencrypt-proxy-companion
    volumes_from:
    - nginx
    volumes:
    - ./certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
    - NGINX_DOCKER_GEN_CONTAINER=redwood-docker-gen
    depends_on:
    - nginx
  redwood-auth-server:
    container_name: redwood-auth-server
    image: quay.io/ucsc_cgl/redwood-auth-server
    environment:
    - VIRTUAL_HOST=auth.${base_url}
    - VIRTUAL_PORT=8443
    - HTTPS_METHOD=nohttp
    - LETSENCRYPT_HOST=auth.${base_url}
    - LETSENCRYPT_EMAIL=${email}
    depends_on:
    - redwood-auth-db
  redwood-auth-db:
    container_name: redwood-auth-db
    image: postgres
    volumes:
    - ./conf/auth-schema-postgresql.sql:/docker-entrypoint-initdb.d/dcc-auth-db.sql
    - ./conf/pg_hba.conf:/etc/postgres/9.6/main/pg_hba.conf
    depends_on:
    - nginx
    - dockergen
    - letsencrypt-proxy-companion
  redwood-metadata-server:
    container_name: redwood-metadata-server
    image: quay.io/ucsc_cgl/redwood-metadata-server
    environment:
    - VIRTUAL_HOST=metadata.${base_url}
    - VIRTUAL_PORT=8444
    - HTTPS_METHOD=nohttp
    - LETSENCRYPT_HOST=metadata.${base_url}
    - LETSENCRYPT_EMAIL=${email}
    depends_on:
    - redwood-metadata-db
    - redwood-auth-server
  redwood-metadata-db:
    container_name: redwood-metadata-db
    image: mongo
    depends_on:
    - nginx
    - dockergen
    - letsencrypt-proxy-companion
  redwood-storage-server:
    container_name: redwood-storage-server
    image: quay.io/ucsc_cgl/redwood-storage-server
    volumes:
    - ./conf/application.storage.properties:/dcc/conf/application.properties
    environment:
    - AWS_ACCESS_KEY_ID=${access_key}
    - AWS_SECRET_ACCESS_KEY=${secret_key}
    - VIRTUAL_HOST=storage.${base_url}
    - VIRTUAL_PORT=5431
    - HTTPS_METHOD=nohttp
    - LETSENCRYPT_HOST=storage.${base_url}
    - LETSENCRYPT_EMAIL=${email}
    depends_on:
    - redwood-auth-server
    - redwood-metadata-server
  metadata-backup:
    container_name: metadata-backup
    image: agmangas/mongo-backup-s3
    environment:
    - FILE_PREFIX=metadata-backup-
    - BACKUP_INTERVAL=1
    - AWS_ACCESS_KEY_ID=${access_key}
    - AWS_SECRET_ACCESS_KEY=${secret_key}
    - S3_BUCKET=${backup_bucket}
    - MONGO_DB=dcc_metadata
    - MONGO_HOST=redwood-metadata-db
    depends_on:
    - redwood-metadata-db
  auth-backup:
    container_name: auth-backup
    image: schickling/postgres-backup-s3
    environment:
    - POSTGRES_HOST=redwood-auth-db
    - POSTGRES_USER=dcc_auth
    - POSTGRES_PASSWORD=${auth_db_password}
    - POSTGRES_DATABASE=dcc
    - S3_PREFIX=auth-backup
    - S3_BUCKET=${backup_bucket}
    - S3_ACCESS_KEY_ID=${access_key}
    - S3_SECRET_ACCESS_KEY=${secret_key}
    depends_on:
    - redwood-auth-db
