#!/usr/bin/env bash
# Usage: project list [-s site]
# Summary: List projects
# Help: This command lists the projects tracked by redwood and managed by the mgmt client.
#
# OPTIONS
#   -s limit results to this redwood site (default: aws)
set -e

site=aws
while getopts ":s:" opt; do
    case $opt in
        s)
            site="${OPTARG}"
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            ;;
    esac
done
shift "$((OPTIND - 1))"

docker exec -it redwood-auth-db psql -tqA -d dcc -U dcc_auth -c "select replace(scope, ',', E'\n') from oauth_client_details where client_id='mgmt';" | cut -d'.' -f 2 | grep -v download | grep -v upload | sort | uniq
# TODO: this will fail for external databases
