sudo: required

services:
 - docker

language: python

before_install:
 - sudo apt-get update
# clone the github repo and cd into it
 - git clone https://github.com/BD2KGenomics/dcc-ops.git
 - cd dcc-ops
 - git checkout feature/add-travis-ci
 - openssl aes-256-cbc -K $encrypted_82facae99918_key -iv $encrypted_82facae99918_iv -in super_secret.txt.enc -out super_secret.txt -d

script:
 - sudo ./install_bootstrap -f

#deploy:
#  provider: releases
#  file: "FILE TO UPLOAD"
#  echo "Begin deploy"
#  skip_cleanup: true
#  on:
#    branch: feature/travis-release-testing

