sudo: required

services:
 - docker

language: python

env:
# Define any environment variables that don't need to be encrypted:
# (consonance.config)
  global:
   - ETH_DEV="ens3"
   - AWS_MAX_SPOT_PRICE="5"
   - FLEET_BATCH_SIZE="2"
   - AWS_REGION="2"
   - AWS_ZONE="us-west-2b"
   - AWS_AMI_IMAGE="ami-6e1a0117"
   - AWS_INSTANCE_TYPE="r4.4xlarge"
   - PEM_PATH="$(pwd)"
   - KEY_NAME="travis-ci-key-pair-aws-dev-box"
   - FLEET_NAME="travis-fleet"
   - FLEET_SIZE="8"
   - CLOUD_ENV="AWS"
   - EMAIL_FOR_VM_OWNER_TAG="travisci@ucsc.edu"
# (redwood.config)
   - BASE_URL="travis-cgp.ucsc-cgp-dev.org"
   - EMAIL_ADDRESS="travisci@ucsc.edu"
   - S3_BUCKET="travis-cgp-redwood-storage"
   - S3_BUCKET_BACKUP="travis-cgp-redwood-backup"
   - S3_ENDPOINT="s3-us-west-2.amazonaws.com"
   - METADATA_DB_HOST="redwood-metadata-db"
   - METADATA_DB="dcc-metadata"
   - METADATA_DB_USERNAME="metadata"
   - AUTH_DB_HOST="redwood-auth-db"
   - AUTH_DB="dcc"
   - AUTH_DB_USERNAME="dcc_auth"
# (boardwalk.config)
   - GOOGLE_CLIENT_ID="abcdefg"
   - GOOGLE_CLIENT_SECRET="ohsosecret"
   - REDWOOD_ADMIN="mgmt"
   - REDWOOD_SERVER="travis-cgp.ucsc-cgp-dev.org"
   - REDWOOD_ENDPOINT="travis-cgp.ucsc-cgp-dev.org"
   - REDWOOD_ADMIN_PORT="443"
   - DCC_DASHBOARD_HOST="travis-cgp.ucsc-cgp-dev.org"
   - DCC_DASHBOARD_PROTOCOL="https"
   - DCC_DASHBOARD_SERVICE="travis-cgp.ucsc-cgp-dev.org"
   - DCC_INVOICING_SERVICE="travis-cgp.ucsc-cgp-dev.org"
   - DCC_ACTION_SERVICE="travis-cgp.ucsc-cgp-dev.org"
   - BILLING_USER="billing_user"
   - BILLING_DB="billing_db"
   - USER_GROUP="1000:1000"
   - ES_SERVICE="elasticsearch1"
   - AWS_PROFILE="travisci@ucsc.edu"
   - POSTGRES_USER="monitor"
   - POSTGRES_DB="monitor"
   - LOGIN_POSTGRES_USER="login-user"
   - LOGIN_POSTGRES_DB="login-db"
   - SERVER_NAME="travis-cgp.ucsc-cgp-dev.org"
   - DCC_CORE_CLIENT_VERSION="1.1.2"
# (action.config)
   - STORAGE_SERVER="travis-cgp.ucsc-cgp-dev.org"
   - ELASTIC_SEARCH_SERVER="elasticsearch1"
   - ELASTIC_SEARCH_PORT="9200"
   - TOUCH_FILE_DIRECTORY="travis-cgp-action-service"

before_install:
 - sudo apt-get update
 - gem --version
# clone the github repo and cd into it
 - git clone https://github.com/BD2KGenomics/dcc-ops.git
 - cd dcc-ops
 - git checkout feature/add-travis-ci

install:
 - sudo apt-get install ruby-full
 - sudo gem install mustache

script:
# Create a file to hold the pem_key
 - printf "%s" "$PEM_KEY" > travis-ci-key-pair-aws-dev-box.pem
# Run install_bootstrap
 - sudo bash install_bootstrap -t
# Bring down the containers afterward
 - sudo docker stop $(sudo docker ps -aq)

