sudo: required

services:
 - docker

language: python

before_install:
 - sudo apt-get update
# clone the github repo and cd into it
 - git clone https://github.com/BD2KGenomics/dcc-ops.git
 - cd dcc-ops
 - git checkout feature/add-travis-ci

script:
 - echo "My secret environment variable is: $test_env_var"
 - echo "Run install_bootstrap"
 - sudo ./install_bootstrap -f

#deploy:
#  provider: releases
#  file: "FILE TO UPLOAD"
#  echo "Begin deploy"
#  skip_cleanup: true
#  on:
#    branch: feature/travis-release-testing

