version: '2'


services:
  postgres:
    image: postgres:9.5
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3.5.6-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default

  webservice:
    build:
      context: .
      dockerfile: Dockerfile_webservice
    container_name: "consonance-webservice"
    ports:
      - "8080:8080"
      - "8081:8081"
    links:
      - postgres
      - rabbitmq
    volumes:
      - log_volume:/consonance_logs
    networks:
      - default
      - esnet

  coordinator:
    build:
      context: .
      dockerfile: Dockerfile_coordinator
    links:
      - webservice
      - rabbitmq
    volumes:
      - log_volume:/consonance_logs
    networks:
      - default

  provisioner:
    build:
      context: .
      dockerfile: Dockerfile_provisioner
    links:
      - webservice
      - rabbitmq
    volumes:
      - log_volume:/consonance_logs
    networks:
      - default

  client:
    build:
      context: .
      dockerfile: Dockerfile_client
    links:
      - webservice
      - postgres
      - coordinator
      - provisioner
    volumes:
      - log_volume:/consonance_logs
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
    networks:
      - default

volumes:
  log_volume:

networks:
  esnet:
    external: true
  default:
    driver: bridge
