version: '2'

services:
  nginx:
    image: nginx:1.11.10
    container_name: core-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    networks:
      - core_public
      - internal
    restart: always
  dockergen:
    image: jwilder/docker-gen:0.7.3
    container_name: core-config-gen
    command: -notify-sighup core-nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    networks:
      - core_public
      - internal
    restart: always
  letsencrypt-nginx-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.6
    container_name: core-letsencrypt-nginx-companion
    volumes_from:
      - nginx
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=core-config-gen
    depends_on:
      - nginx
    networks:
      - core_public
      - internal
    restart: always


networks:
  core_public:
    external: true
  internal:
