version: '2'

services:
  nginx:
    image: nginx:1.11.10
    container_name: core-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    networks:
      - core_public
      - internal
  dockergen:
    image: jwilder/docker-gen:0.7.3
    container_name: core-config-gen
    command: -notify-sighup core-nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    networks:
      - core_public
      - internal

networks:
  core_public:
    external: true
  internal:
