version: '2'

services:
  nginx:
  letsencrypt-nginx-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.4
    container_name: core-letsencrypt-nginx-companion
    volumes_from:
      - nginx
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=core-config-gen
      #- ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory # for staging only
    depends_on:
      - nginx
    networks:
      - core_public
      - internal
