#!/usr/bin/env bash
# Usage: redwood down
# Summary: Stop redwood
# Help: Stop redwood. 
#
# WARNING: This deletes the databases!
set -e

cd "${_REDWOOD_ROOT}/.."
set -x
docker-compose -f base.yml -f db.yml -f prod.yml -f dev.yml down
