version: '2'

# Base redwood server definitions
services:
  redwood-auth-server:
    container_name: redwood-auth-server
    environment:
      - AUTH_DB_HOST=${auth_db_host}
      - AUTH_DB=${auth_db}
      - AUTH_DB_USERNAME=${auth_db_username}
      - AUTH_DB_PASSWORD=${auth_db_password}
      - AUTH_SERVER_ADMIN_PASSWORD=${auth_server_admin_password}
      - AUTH_ADMIN_PASSWORD=${auth_server_admin_password} # TODO: remove upon next auth-server release
      - MGMT_CLIENT_SECRET=${mgmt_client_secret}
      - VIRTUAL_HOST=auth.${base_url}
      - VIRTUAL_PORT=8443
      - HTTPS_METHOD=nohttp
    networks:
      - core_public
      - internal
    restart: always
  redwood-metadata-server:
    container_name: redwood-metadata-server
    environment:
      - METADATA_DB_HOST=${metadata_db_host}
      - METADATA_DB=${metadata_db}
      - METADATA_DB_USERNAME=${metadata_db_username}
      - METADATA_DB_PASSWORD=${metadata_db_password}
      - METADATA_CLIENT_SECRET=${metadata_client_secret}
      - VIRTUAL_HOST=metadata.${base_url}
      - VIRTUAL_PORT=8444
      - HTTPS_METHOD=nohttp
    depends_on:
      - redwood-auth-server
    networks:
      - core_public
      - internal
    restart: always
  redwood-storage-server:
    container_name: redwood-storage-server
    volumes:
      - ./conf/application.storage.properties:/dcc/conf/application-external.properties
    environment:
      - STORAGE_CLIENT_SECRET=${storage_client_secret}
      - AWS_ACCESS_KEY_ID=${access_key}
      - AWS_SECRET_ACCESS_KEY=${secret_key}
      - VIRTUAL_HOST=storage.${base_url}
      - VIRTUAL_PORT=5431
      - HTTPS_METHOD=nohttp
      - REDWOOD_BUCKET=${s3_bucket}
      - REDWOOD_S3_ENDPOINT=${s3_endpoint}
      - REDWOOD_KMS_KEY=${kms_key}
    depends_on:
      - redwood-auth-server
      - redwood-metadata-server
    networks:
      - core_public
      - internal
    restart: always

networks:
  # publicly-accessible containers belong on core_public
  core_public:
    external: true
  # otherwise containers should default to internal
  internal:
