version: '2'
services:
  redwood-auth-server:
    image: quay.io/ucsc_cgl/redwood-auth-server:r4.3.5-SNAPSHOT
    ports:
    - "8443:8443"
    - "8543:8543"
    - "8000:8000"
  redwood-metadata-server:
    image: quay.io/ucsc_cgl/redwood-metadata-server:r0.0.25-SNAPSHOT
    ports:
    - "8444:8444"
    - "8544:8544"
    - "8001:8000"
  redwood-storage-server:
    image: quay.io/ucsc_cgl/redwood-storage-server:r1.0.26-SNAPSHOT
    ports:
    - "5431:5431"
    - "8002:8000"
