version: '2'

services:
  nginx:
    image: nginx:1.11.10
    container_name: redwood-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    networks:
      - internal
    restart: always
  dockergen:
    image: jwilder/docker-gen:0.7.3
    container_name: redwood-config-gen
    command: -notify-sighup redwood-nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf/nginx.dev.tmpl:/etc/docker-gen/templates/nginx.tmpl
    networks:
      - internal
    restart: always
  redwood-auth-server:
    image: quay.io/ucsc_cgl/redwood-auth-server:r4.3.5-SNAPSHOT
    ports:
    - "8443:8443"
    - "8543:8543"
    - "8000:8000"
  redwood-metadata-server:
    image: quay.io/ucsc_cgl/redwood-metadata-server:r0.0.25-SNAPSHOT
    ports:
    - "8444:8444"
    - "8544:8544"
    - "8001:8000"
  redwood-storage-server:
    image: quay.io/ucsc_cgl/redwood-storage-server:r1.0.26-SNAPSHOT
    ports:
    - "5431:5431"
    - "8002:8000"
