version: '2'

# Adds flags for LetsEncrypt cert management
# Uses redwood server releases
services:
  redwood-auth-server:
    image: quay.io/ucsc_cgl/redwood-auth-server:r4.3.4
    environment:
      - LETSENCRYPT_HOST=auth.${base_url}
      - LETSENCRYPT_EMAIL=${email}
  redwood-metadata-server:
    image: quay.io/ucsc_cgl/redwood-metadata-server:r0.0.24
    environment:
    - LETSENCRYPT_HOST=metadata.${base_url}
    - LETSENCRYPT_EMAIL=${email}
  redwood-storage-server:
    image: quay.io/ucsc_cgl/redwood-storage-server:r1.0.25
    environment:
    - LETSENCRYPT_HOST=storage.${base_url}
    - LETSENCRYPT_EMAIL=${email}
