version: '2'
services:
  nginx:
    volumes:
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
  dockergen:
  letsencrypt-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: redwood-letsencrypt-proxy-companion
    volumes_from:
    - nginx
    volumes:
    - ./certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
    - NGINX_DOCKER_GEN_CONTAINER=redwood-docker-gen
    depends_on:
    - nginx
  redwood-auth-server:
    environment:
    - LETSENCRYPT_HOST=auth.${base_url}
    - LETSENCRYPT_EMAIL=${email}
  redwood-auth-db:
    depends_on:
    - letsencrypt-proxy-companion
  redwood-metadata-server:
    environment:
    - LETSENCRYPT_HOST=metadata.${base_url}
    - LETSENCRYPT_EMAIL=${email}
  redwood-metadata-db:
    depends_on:
    - letsencrypt-proxy-companion
  redwood-storage-server:
    environment:
    - AWS_ACCESS_KEY_ID=${access_key}
    - AWS_SECRET_ACCESS_KEY=${secret_key}
    - LETSENCRYPT_HOST=storage.${base_url}
    - LETSENCRYPT_EMAIL=${email}
  metadata-backup:
    container_name: metadata-backup
    image: agmangas/mongo-backup-s3
    environment:
    - FILE_PREFIX=metadata-backup-
    - BACKUP_INTERVAL=1
    - AWS_ACCESS_KEY_ID=${access_key}
    - AWS_SECRET_ACCESS_KEY=${secret_key}
    - S3_BUCKET=${backup_bucket}
    - MONGO_DB=dcc_metadata
    - MONGO_HOST=redwood-metadata-db
    depends_on:
    - redwood-metadata-db
  auth-backup:
    container_name: auth-backup
    image: schickling/postgres-backup-s3
    environment:
    - POSTGRES_HOST=redwood-auth-db
    - POSTGRES_USER=dcc_auth
    - POSTGRES_PASSWORD=${auth_db_password}
    - POSTGRES_DATABASE=dcc
    - S3_PREFIX=auth-backup
    - S3_BUCKET=${backup_bucket}
    - S3_ACCESS_KEY_ID=${access_key}
    - S3_SECRET_ACCESS_KEY=${secret_key}
    depends_on:
    - redwood-auth-db
