#!/usr/bin/env bash
# Usage: sudo redwood install
# Summary: Schedule redwood to start on reboot
# Help: Add `redwood up` to /etc/rc.local. Probably requires sudo
set -e

cmd="${_REDWOOD_ROOT}/bin/redwood up"

if [[ $(grep -c 'redwood up' /etc/rc.local) -gt 0 ]]; then
    echo "ERROR: redwood seems to already have been added to /etc/rc.local - try dcc-ops/redwood/admin/bin/redwood uninstall"
else
    sed "\$i${cmd}" /etc/rc.local > /etc/rc.local.new
    mv /etc/rc.local.new /etc/rc.local
fi
