#!/usr/bin/env bash
# Usage: sudo redwood install
# Summary: Schedule redwood to start on reboot
# Help: Add `redwood up` to /etc/rc.local. Probably requires sudo
set -e

cmd="${_REDWOOD_ROOT}/bin/redwood up"

# uninstall just in case
"${_REDWOOD_ROOT}/bin/redwood uninstall"

# install
sed "\$i${cmd}" /etc/rc.local > /etc/rc.local.new
mv /etc/rc.local.new /etc/rc.local
